name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main # mainブランチにプッシュされたときに実行

jobs:
  build-windows-exe:
    runs-on: windows-latest # Windows環境で実行（.exe作成のため）

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # 使用するPythonのバージョンを指定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller # PyInstallerをインストール

    - name: Build EXE
      run: |
        # PyInstallerでget_gunt.pyをビルド
        # --onefile: 単一のEXEファイルを作成
        # --noconsole: コマンドプロンプトウィンドウを表示しない（GUIアプリ向け、CLIなら不要）
        # その他のオプション: --add-data "path/to/geckodriver;." などでGeckodriverを含めることも可能だが、複雑
        pyinstaller --onefile get_gunt.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: get_gunt-exe
        path: dist/get_gunt.exe # PyInstallerが出力するEXEファイルのパス
